### ISSUE TITLE
How do I set the background color for the collapsable items?

### ISSUE THREAD

**Issue by fortesl** [sherwaniusman/angular-accordion#13]

**Comment by sherwaniusman** [comment]
You need to know about CSS (Cascading Style Sheet). You can edit the file "css/ang-accordion.css" to do visual changes.

**Comment by fortesl** [comment]
Yes, I know I already did that. But it is not maintainable in the long run because if you release an updated version and I want to use it, it will wipe out my changes. It would be cool if you added directive options for changing background and text colors.

**Comment by sherwaniusman** [comment]
You are right. But, when it comes to visual changes, there can be a lot of scenarios and user specific requirements. There's a standard practice, when it comes to editing CSS file of plugin, directive or anything, you always created a separate file for your overridden styles. For example, if you are using bootstrap.css and you want to modify the layout or coloring, you create a separate file (name it override.css) and write all the updated styles in that file and include it after bootstrap.css. In this way, future updates to bootstrap.css will not effect your layout.

**Comment by fortesl** [comment]
That is very reasonable. Thank you!
