### ISSUE TITLE
Need option for removing tooltip 

### ISSUE THREAD

**Issue by fortesl** [sherwaniusman/angular-accordion#14]
In my app the tabs tooltips are not needed. Could we make the tooltips an optional feature?

Thanks.

**Comment by fortesl** [comment]
This issue happens because of the unfortunate usage of the attribute 'title' which is also used by jquery and other popular libraries to display a tooltip. Changing the attribute to 'label' solves this unintended consequence.
 i.e. instead of <collapsible-item title="Heading 1" > use <collapsible-item label="Heading 1" >

**Comment by sherwaniusman** [comment]
Fixed
