### ISSUE TITLE
Issue with initially-open attribute

### ISSUE THREAD

**Issue by jaiswalneha** [sherwaniusman/angular-accordion#20]
Even if the value in initially-open is false, it opens up the collapsible-item.

**Comment by demodav** [comment]
I've found a correction on ln 63 change it to 

scope.isOpenned = (scope.initiallyOpen == "true") ? true : false;

**Comment by sherwaniusman** [comment]
Hi, Thank you for pointing out a solution. The idea was previously, that if you don't want the collapsible item to be opened initially, don't specify it. But still I have updated the repo to support false value as well. Check: https://github.com/sherwaniusman/angular-accordion/commit/1a1ef103d9253d644a85d71f55e82986d270df65

**Comment by SharathVadla** [comment]
Even If I not mentioned initial-open parameter, still the body of accordion is open.
